ZJH/ZJH/urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from user import views as user_views
from  manager import views as manager_views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',user_views.login_view),
    path('user/',include(user_urls)),
    path('logout', user_views.logout),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZJH/user/urls.py
from django.urls import path,include
from user import urls as user_urls
from user import views as user_views
from  student import views as student_views
from  teacher import views as teacher_views
from  manager import views as manager_views

from django.conf import settings
from django.conf.urls.static import static

app_name="user"

urlpatterns = [
    path('sign', user_views.sign_view,name="sign"),
    path('login',user_views.login_view,name="login"),

    path('student/<int:number>',student_views.student_index,name="student"),
    path('student/<int:number>/scanf_information',student_views.student_scanf_information,name="scanf"),
    path('student/<int:number>/change_information',student_views.student_change_information,name="change"),

    path('teacher/<int:number>', teacher_views.teacher_index, name="teacher"),
    path('teacher/<int:number>/scanf_information',teacher_views.teacher_scanf_information,name="t_scanf"),
    path('teacher/<int:number>/change_information', teacher_views.teacher_change_information, name="t_change"),
    path('teacher/<int:number>/login_active', teacher_views.teacher_login_active, name="t_login"),
    path('teacher/<int:number>/scanf_activity', teacher_views.teacher_scanf_active, name="t_scanf_active"),
    path('teacher/<int:number>/delete_activity/<int:activity_id>', teacher_views.teacher_activity_delete, name="t_delete_active"),

    path('manager/<int:number>', manager_views.manager_index, name="manager"),
    path('manager/<int:number>/student_information', manager_views.Student_info.as_view(), name="m_student"),
    path('manager/<int:number>/teacher_information', manager_views.Teacher_info.as_view(), name="m_teacher"),

    path('manager/<int:number>/change_student_information/<int:student_id>', manager_views.manager_change_information, name="m_student_change"),
    path('manager/<int:number>/delete_student_information/<int:student_id>', manager_views.manager_delete_information, name="m_student_delete"),

    path('manager/<int:number>/change_teacher_information/<int:teacher_id>', manager_views.manager_change_teacher_information,
         name="m_teacher_change"),
    path('manager/<int:number>/delete_teacher_information/<int:teacher_id>', manager_views.manager_delete_teacher_information,
         name="m_teacher_delete"),

    path('manager/<int:number>/download_student_information', manager_views.make_sd_csv_view, name="m_sd_download"),
    path('manager/<int:number>/download_teacher_information', manager_views.make_th_csv_view, name="m_th_download"),
    path('manager/<int:number>/download_teacher_information', manager_views.make_th_csv_view, name="m_th_download"),

]

ZJH/templates/manager_change_sd_infor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>更改学生信息</title>
		<link rel="stylesheet" href="{% static 'layui-v2.6.8/layui/css/layui.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/manager_change_sd_infor.css'%}" />
		<script src="{% static 'layui-v2.6.8/layui/layui.js'%}"></script>
		<style>
			/*对layui中的样式进行重写*/
			.layui-tab-content {
				padding: 0;
				/*layui-tab-content:默认有padding: 10px;的值，因为iframe的绝对定位脱离文档流，所以会存在20px的空白空间*/
			}

			.show-frame {
				top: 50px !important;
				/*默认.layui-layout-admin .layui-body {
                top: 60px;
                bottom: 44px;
            }*/
				overflow: hidden;
				/*消除浏览器最右边的滚动条*/
			}

			.frame {
				position: absolute;
				padding: 10px;
				/*与layui-footer隔开一段距离*/
				width: 100%;
				height: 100%;
			}

			.head {
				width: 1280px;
				height: 60px;
				margin: 0 auto;
			}
		</style>
	</head>

	<body>
		<!-- 导航栏 -->
		<div class="layui-layout layui-layout-admin">
			<div class="layui-header head">
				<div class="layui-logo">智慧学工管理平台</div>
				<!-- 头部区域（可配合layui已有的水平导航） -->
				<ul class="layui-nav layui-layout-left">
					<li class="layui-nav-item "><a href="{% url 'user:manager' number %}">首页</a></li>
					<li class="layui-nav-item"><a href="{% url 'user:m_student' number %}">学生信息</a></li>
					<li class="layui-nav-item"><a href="{%  url 'user:m_teacher' number %}">教师信息</a></li>
					<li class="layui-nav-item">
						<a href="javascript:;">下载</a>
						<dl class="layui-nav-child">
							<dd><a href="{% url 'user:m_sd_download' number %}">学生信息</a></dd>
							<dd><a href="{% url 'user:m_th_download' number %}">教师信息</a></dd>
						</dl>
					</li>
				</ul>
				<ul class="layui-nav layui-layout-right">
					<li class="layui-nav-item">
						<a href="/logout">退出登录<span class="layui-badge-dot"></span></a>
					</li>
					<li class="layui-nav-item" lay-unselect="">
						<a href="javascript:;"><img src="{% static 'img/yonghu.png' %}" class="layui-nav-img">欢迎用户&nbsp;{{ number }}</a>
					</li>
				</ul>
			</div>

			<!-- 中间内容 -->
			<div class="content">
				<div class="container layui-form">
					<form action="/user/manager/{{ manager.number }}/change_student_information/{{ student.id }}" method="post" >
						<div class="layui-form-item">
							<label class="layui-form-label">姓名</label>
							<div class="layui-input-block">
								<input type="text" name="name" required lay-verify="required" value="{{ student.name }}" disabled="disabled"
									autocomplete="off" class="layui-input" style="width: 200px;">
							</div>
						</div>

						<div class="layui-form-item">
							<label class="layui-form-label">学号</label>
							<div class="layui-input-block">
								<input type="text" name="number" required lay-verify="required" value="{{ student.number }}" disabled="disabled"
									autocomplete="off" class="layui-input" style="width: 200px;">
							</div>
						</div>

						<div class="layui-form-item">
							<label class="layui-form-label">性别</label>
							<div class="layui-input-block">
								<input type="text" name="sex" required lay-verify="required" value="{{ student.sex }}" disabled="disabled"
									autocomplete="off" class="layui-input" style="width: 200px;">
							</div>
						</div>

						<div class="layui-form-item">
							<label class="layui-form-label">电话</label>
							<div class="layui-input-block">
								<input type="text" name="telephone" required lay-verify="required" value="{{ student.telephone }}"
									autocomplete="off" class="layui-input" style="width: 200px;">
							</div>
						</div>

						<div class="layui-form-item">
							<label class="layui-form-label">关联教师</label>
							<div class="layui-input-block" style="width: 200px;">
								 <select lay-verify=""  style="height: 30px; width:100px;" name="link_teacher">
                                         <option> </option>
                                     {% for teacher in all_teachers %}
                                         <option>{{ teacher.name }}</option>
                                     {% endfor %}
                                 </select>
							</div>
						</div>

						<div class="layui-form-item">
							<div class="layui-input-block">
								<button type="submit" name="submit" class="layui-btn" lay-submit lay-filter="formDemo"
									style="margin-top: 30px;margin-right: 30px;">立即提交</button>
								<button type="reset" name="reset" class="layui-btn layui-btn-primary"
									style="margin-top: 30px;">重置</button>
							</div>
						</div>

					</form>
				</div>
			</div>

			<!-- 尾部 -->
			<div class="foot">
				新疆农业大学计算机与信息工程学院
			</div>
		</div>


		<script src="{% static 'layui-v2.6.8/layui/layui.js' %}"></script>
		<script>
			//JavaScript代码区域
			layui.use(['element,form'], function() {
				var element = layui.element;
				var $ = layui.$;
				$("[name=t1]").click(function() {
					var id = $(this).attr("id");
					var content = $(this).attr("content");
					if ($("li[lay-id=" + id + "]").length == 0) {
						element.tabAdd("empTab", {
							title: $(this).attr("title"),
							content: "<iframe src='" + content +
								"' class='frame' frameborder='0'></iframe>",
							id: id
						})
					}
					element.tabChange('empTab', id)
				})
			});

			layui.use('carousel', function() {
				var carousel = layui.carousel;
				//建造实例
				carousel.render({
					elem: '#test1',
					width: '1080px' //设置容器宽度
						,
					height: '500px' //设置容器高度
						,
					arrow: 'always' //始终显示箭头
						,
					anim: 'default' //切换动画方式
						,
					interval: '2800' //切换时间
				});
			});
		</script>
	</body>

</html>

ZJH/templates/manager_student.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
    <link rel="stylesheet" href="{% static 'layui-v2.6.8/layui/css/layui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/manager_student.css'%}"/>
    <script src="{% static 'layui-v2.6.8/layui/layui.js'%}"></script>
    <style>
       /*对layui中的样式进行重写*/
			.layui-tab-content {
				padding: 0;
				/*layui-tab-content:默认有padding: 10px;的值，因为iframe的绝对定位脱离文档流，所以会存在20px的空白空间*/
			}

			.show-frame {
				top: 50px !important;
				/*默认.layui-layout-admin .layui-body {
                top: 60px;
                bottom: 44px;
            }*/
				overflow: hidden;
				/*消除浏览器最右边的滚动条*/
			}

			.frame {
				position: absolute;
				padding: 10px;
				/*与layui-footer隔开一段距离*/
				width: 100%;
				height: 100%;
			}

			.head {
				width: 1280px;
				height: 60px;
				margin: 0 auto;
			}
    </style>
</head>
<body>
	<!-- 导航栏 -->
		<div class="layui-layout layui-layout-admin">
			<div class="layui-header head">
				<div class="layui-logo">智慧学工管理平台</div>
				<!-- 头部区域（可配合layui已有的水平导航） -->
				<ul class="layui-nav layui-layout-left">
					<li class="layui-nav-item "><a href="{% url 'user:manager' number %}">首页</a></li>
					<li class="layui-nav-item"><a href="{% url 'user:m_student' number %}">学生信息</a></li>
					<li class="layui-nav-item"><a href="{% url 'user:m_teacher' number %}">教师信息</a></li>
					<li class="layui-nav-item">
						<a href="javascript:;">下载</a>
						<dl class="layui-nav-child">
							<dd><a href="{% url 'user:m_sd_download' number %}">学生信息</a></dd>
							<dd><a href="{%  url 'user:m_th_download' number %}">教师信息</a></dd>
						</dl>
					</li>
				</ul>
				<ul class="layui-nav layui-layout-right">
					<li class="layui-nav-item">
						<a href="/logout">退出登录<span class="layui-badge-dot"></span></a>
					</li>
					<li class="layui-nav-item" lay-unselect="">
						<a href="javascript:;"><img src="{% static 'img/yonghu.png' %}" class="layui-nav-img">欢迎用户&nbsp;{{ number }}</a>
					</li>
				</ul>
			</div>

			<!-- 中间内容 -->
			<div class="content">
				<div class="container">
					<form action="" method="get">
						<span>姓名：</span><input type="text" name="姓名">
						<span>学号：</span><input type="text" name="学号">
						<input type="submit" value="查找">
                        <a class="layui-btn" style="height: 35px; line-height: 35px;"
							href="http://baidu.com">添加学生</a>
					</form>
					<table>
						<table class="layui-table change">
							<thead>
								<tr>
									<th>姓名</th>
									<th>学号</th>
									<th>性别</th>
									<th>电话</th>
									<th>关联教师</th>
                                    <th>操作</th>
								</tr>
							</thead>
							<tbody>
								{% for student in good_students %}
								<tr>
									<td>{{ student.name }}</td>
									<td>{{ student.number }}</td>
									<td>{{ student.sex }}</td>
									<td>{{ student.telephone }}</td>
                                    <td>{{ student.link_teacher.name }}</td>
									<td>
										<a class="layui-btn layui-btn-sm layui-btn-radius layui-btn-normal"
											href="{% url 'user:m_student_change' number  student.id %}">编辑</a>
										<a class="layui-btn layui-btn-sm layui-btn-radius layui-btn-danger"
                                            href="{% url 'user:m_student_delete' number student.id %}">删除</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</table>
				</div>
			</div>

			<!-- 尾部 -->
			<div class="foot">
				新疆农业大学计算机与信息工程学院
			</div>
		</div>


		<script src="{% static 'layui-v2.6.8/layui/layui.js' %}"></script>
		<script>
			//JavaScript代码区域
			layui.use('element', function() {
				var element = layui.element;
				var $ = layui.$;
				$("[name=t1]").click(function() {
					var id = $(this).attr("id");
					var content = $(this).attr("content");
					if ($("li[lay-id=" + id + "]").length == 0) {
						element.tabAdd("empTab", {
							title: $(this).attr("title"),
							content: "<iframe src='" + content +
								"' class='frame' frameborder='0'></iframe>",
							id: id
						})
					}
					element.tabChange('empTab', id)
				})
			});

			layui.use('carousel', function() {
				var carousel = layui.carousel;
				//建造实例
				carousel.render({
					elem: '#test1',
					width: '1080px' //设置容器宽度
						,
					height: '500px' //设置容器高度
						,
					arrow: 'always' //始终显示箭头
						,
					anim: 'default' //切换动画方式
						,
					interval: '2800' //切换时间
				});
			});
		</script>
</body>
</html>

ZJH/templates/manager_teacher.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>教师信息</title>
		<link rel="stylesheet" type="text/css" href="{% static 'layui-v2.6.8/layui/css/layui.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/manager_teacher.css'%}" />
		<script src="{% static 'layui-v2.6.8/layui/layui.js'%}"></script>
		<style>
			/*对layui中的样式进行重写*/
			.layui-tab-content {
				padding: 0;
				/*layui-tab-content:默认有padding: 10px;的值，因为iframe的绝对定位脱离文档流，所以会存在20px的空白空间*/
			}

			.show-frame {
				top: 50px !important;
				/*默认.layui-layout-admin .layui-body {
                top: 60px;
                bottom: 44px;
            }*/
				overflow: hidden;
				/*消除浏览器最右边的滚动条*/
			}

			.frame {
				position: absolute;
				padding: 10px;
				/*与layui-footer隔开一段距离*/
				width: 100%;
				height: 100%;
			}

			.head {
				width: 1280px;
				height: 60px;
				margin: 0 auto;
			}
		</style>
	</head>

	<body>
		<!-- 导航栏 -->
		<div class="layui-layout layui-layout-admin">
			<div class="layui-header head">
				<div class="layui-logo">智慧学工管理平台</div>
				<!-- 头部区域（可配合layui已有的水平导航） -->
				<ul class="layui-nav layui-layout-left">
					<li class="layui-nav-item "><a href="{% url 'user:manager' number %}">首页</a></li>
					<li class="layui-nav-item"><a href="{% url 'user:m_student' number %}">学生信息</a></li>
					<li class="layui-nav-item"><a href="{% url 'user:m_teacher' number %}">教师信息</a></li>
					<li class="layui-nav-item">
						<a href="javascript:;">下载</a>
						<dl class="layui-nav-child">
							<dd><a href="{% url 'user:m_sd_download' number %}">学生信息</a></dd>
							<dd><a href="{% url 'user:m_th_download' number %}">教师信息</a></dd>
						</dl>
					</li>
				</ul>
				<ul class="layui-nav layui-layout-right">
					<li class="layui-nav-item">
						<a href="/logout">退出登录<span class="layui-badge-dot"></span></a>
					</li>
					<li class="layui-nav-item" lay-unselect="">
						<a href="javascript:;"><img src="{% static 'img/yonghu.png' %}" class="layui-nav-img">欢迎用户&nbsp;{{ number }}</a>
					</li>
				</ul>
			</div>

			<!-- 中间内容 -->
			<div class="content">
				<div class="container">
					<form action="" method="get">
						<span>姓名：</span><input type="text" name="姓名">
						<span>工号：</span><input type="text" name="学号">
						<input type="submit" value="查找">
					</form>
					<table>
						<table class="layui-table change">
							<thead>
								<tr>
									<th>姓名</th>
									<th>工号</th>
									<th>性别</th>
									<th>电话</th>
									<th>操作</th>

								</tr>
							</thead>
							<tbody>
								{% for teacher in good_teachers %}
								<tr>
									<td>{{ teacher.name }}</td>
									<td>{{ teacher.number }}</td>
									<td>{{ teacher.sex }}</td>
									<td>{{ teacher.telephone }}</td>
									<td>
										<a class="layui-btn layui-btn-sm layui-btn-radius layui-btn-normal"
											href="{% url 'user:m_teacher_change' number  teacher.id %}">编辑</a>
										<a class="layui-btn layui-btn-sm layui-btn-radius layui-btn-danger"
                                            href="{% url 'user:m_teacher_delete' number teacher.id %}">删除</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</table>
				</div>
			</div>

			<!-- 尾部 -->
			<div class="foot">
				新疆农业大学计算机与信息工程学院
			</div>
		</div>


		<script src="{% static 'layui-v2.6.8/layui/layui.js'%}"></script>
		<script>
			//JavaScript代码区域
			layui.use('element', function() {
				var element = layui.element;
				var $ = layui.$;
				$("[name=t1]").click(function() {
					var id = $(this).attr("id");
					var content = $(this).attr("content");
					if ($("li[lay-id=" + id + "]").length == 0) {
						element.tabAdd("empTab", {
							title: $(this).attr("title"),
							content: "<iframe src='" + content +
								"' class='frame' frameborder='0'></iframe>",
							id: id
						})
					}
					element.tabChange('empTab', id)
				})
			});

			layui.use('carousel', function() {
				var carousel = layui.carousel;
				//建造实例
				carousel.render({
					elem: '#test1',
					width: '1080px' //设置容器宽度
						,
					height: '500px' //设置容器高度
						,
					arrow: 'always' //始终显示箭头
						,
					anim: 'default' //切换动画方式
						,
					interval: '2800' //切换时间
				});
			});
		</script>
	</body>

</html>

ZJH/templates/teacher_activity_info.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>教师活动记录</title>
    <link rel="stylesheet" href="{% static 'layui-v2.6.8/layui/css/layui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/teacher_activity_info.css' %}"/>
    <script src="{% static 'layui-v2.6.8/layui/layui.js' %}"></script>
    <style>
        /*对layui中的样式进行重写*/
        .layui-tab-content {
            padding: 0;
            /*layui-tab-content:默认有padding: 10px;的值，因为iframe的绝对定位脱离文档流，所以会存在20px的空白空间*/
        }

        .show-frame {
            top: 50px !important;
            /*默认.layui-layout-admin .layui-body {
            top: 60px;
            bottom: 44px;
        }*/
            overflow: hidden;
            /*消除浏览器最右边的滚动条*/
        }

        .frame {
            position: absolute;
            padding: 10px;
            /*与layui-footer隔开一段距离*/
            width: 100%;
            height: 100%;
        }

        .head {
            width: 1280px;
            height: 60px;
            margin: 0 auto;
        }
    </style>
</head>

<body>
<div class="layui-layout layui-layout-admin">
    <!-- 导航栏 -->
    <div class="layui-header head">
        <div class="layui-logo">智慧学工管理平台</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item "><a href="{% url 'user:teacher' number %}">首页</a></li>
            <li class="layui-nav-item"><a href="{% url 'user:t_scanf' number %}">查看个人信息</a></li>
            <li class="layui-nav-item"><a href="{% url 'user:t_change' number %}">更改个人信息</a></li>
            <li class="layui-nav-item"><a href="{% url 'user:t_login' number %}">上传活动</a></li>
            <li class="layui-nav-item"><a href="{% url 'user:t_scanf_active' number %}">活动记录</a></li>
            <li class="layui-nav-item">
                <a href="javascript:;">其它系统</a>
                <dl class="layui-nav-child">
                    <dd><a href="">暂无功能</a></dd>
                    <dd><a href="">暂无功能</a></dd>
                    <dd><a href="">暂无功能</a></dd>
                </dl>
            </li>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="/logout">退出登录<span class="layui-badge-dot"></span></a>
            </li>
            <li class="layui-nav-item" lay-unselect="">
                <a href="javascript:;"><img src="{% static 'img/yonghu.png' %}"
                                            class="layui-nav-img">欢迎用户&nbsp;{{ number }}</a>
            </li>
        </ul>
    </div>


    <div class="wrapper">
        {% for ac in activity %}
            <div class="container">
                <div class="box">
                    <div class="left" style="background-image: url('/media/{{ ac.image }}')"></div>
                    <div class="right">
                        <div class="title">
                            活动类型：{{ ac.type }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            活动主题：{{ ac.title }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            活动对象：{{ ac.people }}
                        </div>
                        <div class="content">
                            {{ ac.content }}
                        </div>
                        <div class="bottom">发布者：
                            <span class="name">{{ teacher.name }}</span>
                            <a href="{% url 'user:t_delete_active' number ac.id%}" style="float: right;margin-left: 20px;color:#6C757D;">删除</a>
                            <span class="time">{{ ac.created_time }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>




    <!-- 尾部 -->
    <div class="foot">
        新疆农业大学计算机与信息工程学院
    </div>
</div>
</body>
</html>

ZJH/templates/teacher_information_change.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>教师个人信息更改</title>
    <link rel="stylesheet" href="{% static 'layui-v2.6.8/layui/css/layui.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/teacher_information_change.css'%}"/>
    <script src="{% static 'layui-v2.6.8/layui/layui.js'%}"></script>
    <style>
        /*对layui中的样式进行重写*/
        .layui-tab-content {
            padding: 0;/*layui-tab-content:默认有padding: 10px;的值，因为iframe的绝对定位脱离文档流，所以会存在20px的空白空间*/
        }
        .show-frame {
            top: 50px!important;
            /*默认.layui-layout-admin .layui-body {
                top: 60px;
                bottom: 44px;
            }*/
            overflow: hidden;/*消除浏览器最右边的滚动条*/
        }
        .frame {
            position: absolute;
            padding: 10px;/*与layui-footer隔开一段距离*/
            width: 100%;
            height: 100%;
        }
		.head{
			width: 1280px;
			height: 60px;
			margin: 0 auto;
		}
    </style>
</head>

<body>

	<div class="layui-layout layui-layout-admin">
		<!-- 导航栏 -->
		<div class="layui-header head">
			<div class="layui-logo">智慧学工管理平台</div>
			<!-- 头部区域（可配合layui已有的水平导航） -->
			<ul class="layui-nav layui-layout-left">
				<li class="layui-nav-item "><a href="{% url 'user:teacher' number %}">首页</a></li>
				<li class="layui-nav-item"><a href="{% url 'user:t_scanf' number %}">查看个人信息</a></li>
				<li class="layui-nav-item"><a href="{% url 'user:t_change' number%}">更改个人信息</a></li>
				<li class="layui-nav-item"><a href="{% url 'user:t_login' number %}">上传活动</a></li>
				<li class="layui-nav-item"><a href="{% url 'user:t_scanf_active' number %}">活动记录</a></li>
				<li class="layui-nav-item">
					<a href="javascript:;">其它系统</a>
					<dl class="layui-nav-child">
						<dd><a href="">暂无功能</a></dd>
						<dd><a href="">暂无功能</a></dd>
						<dd><a href="">暂无功能</a></dd>
					</dl>
				</li>
			</ul>
			<ul class="layui-nav layui-layout-right">
				<li class="layui-nav-item">
					<a href="/logout">退出登录<span class="layui-badge-dot"></span></a>
				</li>
				<li class="layui-nav-item" lay-unselect="">
					<a href="javascript:;"><img src="{% static 'img/yonghu.png' %}" class="layui-nav-img">欢迎用户&nbsp;{{ number }}</a>
				</li>
			</ul>
		</div>


		<div class="content" style="background-color: #E2E2E2">
			<table border="3" width="800" height="600" align="center" bgcolor="#F1F3F4" style="-webkit-box-shadow: 0px 0px 10px -2px rgb(158 158 158);
	box-shadow: 0px 0px 10px -2px rgb(158 158 158 );">
				<form action="/user/teacher/{{ teacher_change.number }}/change_information" method="post">
					<tr class="font1">
						<td colspan="6" align="center">更改个人信息</td>
					</tr>
					<tr align="center">
						<td class="font1">&nbsp;&nbsp;&nbsp;&nbsp;姓名&nbsp;&nbsp;&nbsp;&nbsp;</td>
						<td><input type="text"  name="name" value="{{ teacher_change.name }}" style="height: 25px; text-align: center;"/></td>
						<td class="font1">&nbsp;&nbsp;&nbsp;&nbsp;性别&nbsp;&nbsp;&nbsp;&nbsp;</td>
						<td><input type="text" name="sex" value="{{ teacher_change.sex }}" style="height: 25px; text-align: center;"/></td>
						<td class="font1">&nbsp;&nbsp;&nbsp;&nbsp;民族&nbsp;&nbsp;&nbsp;&nbsp;</td>
						<td><input type="text" name="person" value="{{ teacher_change.person }}" style="height: 25px; text-align: center;" /></td>
					</tr>
					<tr align="center">
						<td class="font1">工号</td>
						<td><input type="text" name="number"  value="{{ teacher_change.number }}" disabled="disabled" style="height: 25px; text-align: center;"/></td>
						<td class="font1">密码</td>
						<td><input type="text" name="password" value="{{ teacher_change.password }}"  disabled="disabled" style="height: 25px; text-align: center;"/></td>
						<td class="font1">职务</td>
						<td><input type="text" name="job" value="{{ teacher_change.job }}"  style="height: 25px; text-align: center;" disabled="disabled"/></td>
					</tr>
					<tr align="center">
						<td class="font1">学院</td>
						<td><input type="text" name="colleage" value="{{ teacher_change.colleage }}" style="height: 25px; text-align: center;" /></td>
						<td class="font1">年龄</td>
						<td><input type="text" name="age" value="{{ teacher_change.age }}"  style="height: 25px; text-align: center;"/></td>
						<td class="font1">电话</td>
						<td><input type="text" name="telephone" value="{{ teacher_change.telephone }}"  style="height: 25px; text-align: center;"/></td>
					</tr>
					<tr class="font1">
						<td colspan="6" align="center">
							<input type="submit" name="submit" value="提交" style="height: 40px; width:100px;border:2px solid;"/>
						</td>
					</tr>
				</form>
			</table>
		</div>
		<!-- 尾部 -->
		<div class="foot">
			新疆农业大学计算机与信息工程学院
		</div>
	</div>

</body>
</html>